var famdata = [
    { id: 1, title: "Bruno", label: "Bruno Fagundes", image: "demo/images/photos/b.png", description: "3, Sr. VP, Server & Tools Division", itemTitleColor: "#4b0082"},
    { id: 2, parents: [1], title: "Vera", image: "demo/images/photos/v.png", itemTitleColor: "#4b0082" },
    { id: 3, parents: [1], title: "Julio", image: "demo/images/photos/j.png", itemTitleColor: "#4b0082" },
    { id: 4, parents: [3], title: "Gessy", image: "demo/images/photos/g.png", itemTitleColor: "#4b0082" },
    { id: 5, parents: [3], title: "Joao", image: "demo/images/photos/j.png", itemTitleColor: "#4b0082" },
    { id: 6, parents: [2,25,26,27,28,29,30,31,63], title: "Enilda", image: "demo/images/photos/e.png", itemTitleColor: "#4b0082" },
    { id: 7, parents: [2,25,26,27,28,29,30,31,63], title: "Olinto", image: "demo/images/photos/o.png", itemTitleColor: "#4b0082" },
    { id: 8, parents: [5], title: "Adao", image: "demo/images/photos/a.png", itemTitleColor: "#4b0082" },
    { id: 9, parents: [5], title: "Maria", image: "demo/images/photos/m.png", itemTitleColor: "#4b0082" },
    { id: 10, parents: [4], title: "Ary", image: "demo/images/photos/a.png", itemTitleColor: "#4b0082" },
    { id: 11, parents: [4], title: "Dorvalina", image: "demo/images/photos/d.png", itemTitleColor: "#4b0082" },
    { id: 12, parents: [7], title: "Edison", image: "demo/images/photos/e.png", itemTitleColor: "#4b0082" },
    { id: 13, parents: [7], title: "Maria Joaquina", image: "demo/images/photos/m.png", itemTitleColor: "#4b0082" },
    { id: 14, parents: [6,22], title: "Adrião", image: "demo/images/photos/a.png", itemTitleColor: "#4b0082" },
    { id: 15, parents: [6,22], title: "Maria Vergilio", image: "demo/images/photos/m.png", itemTitleColor: "#4b0082" },
    { id: 16, parents: [13], title: "Severo", image: "demo/images/photos/s.png", itemTitleColor: "#4b0082" },
    { id: 17, parents: [14], title: "Malvino", image: "demo/images/photos/m.png", itemTitleColor: "#4b0082" },
    { id: 18, parents: [14], title: "Rita", image: "demo/images/photos/r.png", itemTitleColor: "#4b0082" },
    { id: 19, parents: [15], title: "Luiz Vergilio", image: "demo/images/photos/l.png", itemTitleColor: "#4b0082" },
    { id: 20, parents: [15], title: "Josefina Vergilio", image: "demo/images/photos/j.png", itemTitleColor: "#4b0082" },
    { id: 21, parents: [16,19], title: "?", image: "demo/images/photos/x.png", itemTitleColor: "#4b0082" },
    { id: 22, parents: [24], title: "Darci", image: "demo/images/photos/d.png" },
    { id: 23, parents: [24], title: "Zulmira", image: "demo/images/photos/z.png" },
    { id: 24, parents: [57], title: "Neusa", image: "demo/images/photos/n.png" },
    { id: 25, parents: [35,36,37], title: "Enio", image: "demo/images/photos/e.png" },
    { id: 26, title: "Maria", image: "demo/images/photos/m.png" },
    { id: 27, title: "Noeli", image: "demo/images/photos/n.png" },
    { id: 28, parents: [39,40], title: "Norma", image: "demo/images/photos/n.png" },
    { id: 29, parents: [52,53], title: "Eneida", image: "demo/images/photos/e.png" },
    { id: 30, parents: [59,60,61], title: "Helena", image: "demo/images/photos/h.png" },
    { id: 31, parents: [33], title: "Gilca", image: "demo/images/photos/h.png" },
    { id: 32, parents: [33], title: "Benito", image: "demo/images/photos/b.png" },
    { id: 33, parents: [71], title: "Jônata", image: "demo/images/photos/j.png" },
    { id: 34, parents: [35,36,37], title: "Adair", image: "demo/images/photos/a.png" },
    { id: 35, parents: [49], title: "Isaura", image: "demo/images/photos/i.png" },
    { id: 36, parents: [50], title: "Rosaura", image: "demo/images/photos/r.png" },
    { id: 37, parents: [48], title: "Gustavo", image: "demo/images/photos/g.png" },
    { id: 38, parents: [39,40], title: "Itamar", image: "demo/images/photos/i.png" },
    { id: 39, parents: [42], title: "Ana", image: "demo/images/photos/a.png" },
    { id: 40, parents: [44], title: "Claiton", image: "demo/images/photos/c.png" },
    { id: 41, parents: [42], title: "Carlos", image: "demo/images/photos/c.png" },
    { id: 42, title: "Pedro", image: "demo/images/photos/p.png" },
    { id: 43, parents: [44], title: "Bianca", image: "demo/images/photos/b.png" },
    { id: 44, title: "Alessandra", image: "demo/images/photos/a.png" },
    { id: 45, parents: [49], title: "José", image: "demo/images/photos/j.png" },
    { id: 46, parents: [50], title: "Cristiano", image: "demo/images/photos/c.png" },
    { id: 47, parents: [48], title: "?", image: "demo/images/photos/a.png" },
    { id: 48, title: "?", image: "demo/images/photos/a.png" },
    { id: 49, title: "Zezinho", image: "demo/images/photos/z.png" },
    { id: 50, title: "Luizinho", image: "demo/images/photos/l.png" },
    { id: 51, parents: [52,53], title: "?", image: "demo/images/photos/a.png" },
    { id: 52, title: "Fernando", image: "demo/images/photos/a.png" },
    { id: 53, parents: [55], title: "Marcia", image: "demo/images/photos/a.png" },
    { id: 54, parents: [55], title: "Fabio", image: "demo/images/photos/a.png" },
    { id: 55, title: "Felipe", image: "demo/images/photos/a.png" },
    { id: 56, parents: [57], title: "?", image: "demo/images/photos/a.png" },
    { id: 57, title: "João", image: "demo/images/photos/a.png" },
    { id: 58, parents: [59,60,61], title: "Luiz", image: "demo/images/photos/a.png" },
    { id: 59, title: "Carla", image: "demo/images/photos/a.png" },
    { id: 60, parents: [72], title: "Fabiana", image: "demo/images/photos/a.png" },
    { id: 61, title: "Alex", image: "demo/images/photos/a.png" },
    { id: 62, parents: [72], title: "?", image: "demo/images/photos/a.png" },
    { id: 63, parents: [65,66], title: "Eni", image: "demo/images/photos/a.png" },
    { id: 64, parents: [65,66], title: "?", image: "demo/images/photos/a.png" },
    { id: 65, title: "Lidia", image: "demo/images/photos/a.png" },
    { id: 66, parents: [69], title: "Ligia", image: "demo/images/photos/a.png" },
    { id: 67, parents: [69], title: "Francisco", image: "demo/images/photos/a.png" },
    { id: 68, title: "Erisvan", image: "demo/images/photos/a.png" },
    { id: 69, title: "Larissa", image: "demo/images/photos/a.png" },
    { id: 70, parents: [71], title: "Monica", image: "demo/images/photos/a.png" },
    { id: 71, title: "?", image: "demo/images/photos/a.png" },
    { id: 72, title: "?", image: "demo/images/photos/a.png" },
    { id: 73, parents: [16,19], title: "?", image: "demo/images/photos/a.png", itemTitleColor: "#4b0082" },
    // como juntar o 65 e o 68 sem filhos? | spouses: [65], 
];